# Generated by Django 4.0.3 on 2022-03-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
