# Generated by Django 4.0.3 on 2022-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
