# Generated by Django 4.0.3 on 2022-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_is_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_working',
        ),
        migrations.AddField(
            model_name='post',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
