# Generated by Django 4.0.3 on 2022-03-16 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_complete_post_iofield_post_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
