# Generated by Django 4.0.3 on 2022-03-16 10:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='iofield',
            new_name='explanation',
        ),
        migrations.AddField(
            model_name='post',
            name='inputfield',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='outputfield',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
