# Generated by Django 4.0.3 on 2022-03-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='inputfield',
        ),
        migrations.RemoveField(
            model_name='post',
            name='outputfield',
        ),
    ]
