# Generated by Django 4.0.3 on 2022-03-31 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_commentcpp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcpp',
            old_name='category',
            new_name='categorycpp',
        ),
        migrations.RemoveField(
            model_name='categorycpp',
            name='title',
        ),
        migrations.RemoveField(
            model_name='commentcpp',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcpp',
            name='title',
        ),
        migrations.AddField(
            model_name='categorycpp',
            name='titlecpp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titlecpp'),
        ),
        migrations.AddField(
            model_name='commentcpp',
            name='postcpp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentscpp', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcpp',
            name='titlecpp',
            field=models.CharField(default=1, max_length=150, verbose_name='Titlecpp'),
            preserve_default=False,
        ),
    ]
