# Generated by Django 4.0.3 on 2022-04-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_categoryjava_categorypython_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcpp',
            old_name='likes',
            new_name='likescpp',
        ),
        migrations.RenameField(
            model_name='postcpp',
            old_name='saves',
            new_name='savescpp',
        ),
    ]
