# Generated by Django 4.0.3 on 2022-04-17 06:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_rename_likes_postcpp_likescpp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryleetcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleleetcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titleleetcode')),
            ],
        ),
        migrations.CreateModel(
            name='Postleetcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleleetcode', models.CharField(max_length=150, verbose_name='Titleleetcode')),
                ('categoryleetcode', models.CharField(default='coding', max_length=255)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('level', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('videolink', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('topics', models.CharField(default='sample', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='blogpostleetcode', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='blogsaveleetcode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentleetcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='blogcommentleetcode', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postleetcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsleetcode', to='blog.post')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.commentleetcode')),
            ],
        ),
    ]
