# Generated by Django 4.0.3 on 2022-04-17 12:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_categoryleetcode_postleetcode_commentleetcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postleetcode',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='postleetcode',
            old_name='link',
            new_name='content10',
        ),
        migrations.RenameField(
            model_name='postleetcode',
            old_name='videolink',
            new_name='content2',
        ),
        migrations.RenameField(
            model_name='postleetcode',
            old_name='titleleetcode',
            new_name='titleleetcode1',
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='content3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='content4',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='content5',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='content6',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='content7',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='content8',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='content9',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link10',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link4',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link5',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link6',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link7',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link8',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='link9',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='titleleetcode10',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Titleleetcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='titleleetcode2',
            field=models.CharField(default=1, max_length=150, verbose_name='Titleleetcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='titleleetcode3',
            field=models.CharField(default=1, max_length=150, verbose_name='Titleleetcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='titleleetcode4',
            field=models.CharField(default=1, max_length=150, verbose_name='Titleleetcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='titleleetcode5',
            field=models.CharField(default=1, max_length=150, verbose_name='Titleleetcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='titleleetcode6',
            field=models.CharField(default=1, max_length=150, verbose_name='Titleleetcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='titleleetcode7',
            field=models.CharField(default=1, max_length=150, verbose_name='Titleleetcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='titleleetcode8',
            field=models.CharField(default=1, max_length=150, verbose_name='Titleleetcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='titleleetcode9',
            field=models.CharField(default=1, max_length=150, verbose_name='Titleleetcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink10',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink4',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink5',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink6',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink7',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink8',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postleetcode',
            name='videolink9',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentleetcode',
            name='postleetcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsleetcode', to='blog.postleetcode'),
        ),
    ]
