# Generated by Django 4.0.3 on 2022-04-24 06:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0022_rename_content_postleetcode_content1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postlb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlelb1', models.CharField(max_length=150, verbose_name='Titlelb')),
                ('titlelb2', models.CharField(max_length=150, verbose_name='Titlelb')),
                ('titlelb3', models.CharField(max_length=150, verbose_name='Titlelb')),
                ('titlelb4', models.CharField(max_length=150, verbose_name='Titlelb')),
                ('categorylb', models.CharField(default='coding', max_length=255)),
                ('linklb1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('linklb2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('linklb3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('linklb4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('topics', models.CharField(default='sample', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='blogpostlb', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='blogsavelb', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentlb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='blogcommentlb', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postlb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentslb', to='blog.postlb')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.commentlb')),
            ],
        ),
    ]
