from django.contrib import admin
from .models import Categoryjava, Categorylb, Categoryleetcode, Categorypython, Comment, Commentjava, Commentlb, Commentpython, Post, Category,Postcpp,Categorycpp,Commentcpp, Postjava, Postlb, Postleetcode, Postpython,Commentleetcode
admin.site.register(Post)
admin.site.register(Comment)
admin.site.register(Category)
admin.site.register(Postleetcode)
admin.site.register(Commentleetcode)
admin.site.register(Categoryleetcode)
admin.site.register(Postcpp)
admin.site.register(Commentcpp)
admin.site.register(Categorycpp)
admin.site.register(Postjava)
admin.site.register(Commentjava)
admin.site.register(Categoryjava)
admin.site.register(Postpython)
admin.site.register(Commentpython)
admin.site.register(Categorypython)
admin.site.register(Postlb)
admin.site.register(Commentlb)
admin.site.register(Categorylb)
