from django.urls import path
from . import views
from .views import AllSaveView, AllSaveViewPython, AllSaveViewjava, LikeCommentViewcpp, LikeCommentViewjava, LikeCommentViewpython, LikeViewlb, PostCreateViewjava, PostCreateViewlb, PostCreateViewpython, PostDetailViewcpp, PostDetailViewjava, PostDetailViewlb, PostDetailViewpython, PostListView, PostDetailView, PostCreateView,PostCreateViewcpp,PostUpdateView, PostDeleteView, SaveView, SaveViewcpp, SaveViewjava, SaveViewpython, UserPostListView, LikeView,LikeCommentView, posts_of_following_profiles,  AllLikeView,category_list,category_detail,AddCategoryView,CategoryView,CategoryViewcpp,CategoryViewjava,CategoryViewpython,CategoryListView,cut,uncut,languages,CategoryListViewcpp,CategoryListViewjava,CategoryListViewpython,LikeViewcpp,LikeViewjava,LikeViewpython,AllLikeViewcpp,AllLikeViewjava,AllLikeViewpython,AllSaveViewcpp,LikeViewcpp,PostCreateViewleetcode,PostDetailViewleetcode,LikeViewleetcode,CategoryListViewleetcode,CategoryViewleetcode,CategoryListViewlb,randomdsa,randomcf,randomcfratingmain,randomcfrating,cfuserdetails,cfcontests,contact

from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
urlpatterns = [
    path('', views.first, name='firsthome'),
    path('^category$', views.category_list, name='category_list'),
    path('^category$', views.category_list_leetcode, name='category_list_leetcode'),
    path('category/(?P<pk>\d+)/$', views.category_detail, name='category_detail'),
    path('add_category', AddCategoryView.as_view(),name="add_category"),
    path('category/<str:cats>/', CategoryView, name="category"),
    path('categoryleetcode/<str:cats>/', CategoryViewleetcode, name="category-leetcode"),
    path('category/<str:cats>/cpp', CategoryViewcpp, name="category-cpp"),
    path('category/<str:cats>/java', CategoryViewjava, name="category-java"),
    path('category/<str:cats>/python', CategoryViewpython, name="category-python"),
    path('topics/list/leetcode', CategoryListViewleetcode, name='category-list-leetcode'),
    path('topics/list/logic-building', CategoryListViewlb, name='category-list-lb'),
    path('topics/list/', CategoryListView, name='category-list'),
    path('topics/list/cpp', CategoryListViewcpp, name='category-list-cpp'),
    path('topics/list/java', CategoryListViewjava, name='category-list-java'),
    path('topics/list/python', CategoryListViewpython, name='category-list-python'),
    path('cut/<list_id>',views.cut,name="cut"),
    path('uncut/<list_id>',views.uncut,name="uncut"),
    path('home/', PostListView.as_view(), name='blog-home'),
    path('feed/', posts_of_following_profiles, name='posts-follow-view'),
    path('post/user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView, name='post-detail'),
    path('post/leetcode/<int:pk>/', PostDetailViewleetcode, name='post-detail-leetcode'),
    path('post/logic-building/<int:pk>/', PostDetailViewlb, name='post-detail-lb'),
    path('post/cpp/<int:pk>/', PostDetailViewcpp, name='post-detail-cpp'),
    path('post/java/<int:pk>/', PostDetailViewjava, name='post-detail-java'),
    path('post/python/<int:pk>/', PostDetailViewpython, name='post-detail-python'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/new/leetcode', PostCreateViewleetcode.as_view(), name='post-create-leetcode'),
    path('post/new/logic-building', PostCreateViewlb.as_view(), name='post-create-lb'),
    path('post/new/cpp', PostCreateViewcpp.as_view(), name='post-create-cpp'),
    path('post/new/java', PostCreateViewjava.as_view(), name='post-create-java'),
    path('post/new/python', PostCreateViewpython.as_view(), name='post-create-python'),
    path('post/like/cpp', LikeViewcpp, name='post-like-cpp'),
    path('post/like/', LikeView, name='post-like'),
    path('post/like/leetcode', LikeViewleetcode, name='post-like-leetcode'),
    path('post/like/logic-building', LikeViewlb, name='post-like-lb'),
    path('post/like/java', LikeViewjava, name='post-like-java'),
    path('post/like/python', LikeViewpython, name='post-like-python'),
    path('liked-posts/', AllLikeView, name='all-like'),
    path('liked-posts/cpp', AllLikeViewcpp, name='all-like-cpp'),
    path('liked-posts/java', AllLikeViewjava, name='all-like-java'),
    path('liked-posts/python', AllLikeViewpython, name='all-like-python'),
    path('post/save/', SaveView, name='post-save'),
    path('post/save/cpp', SaveViewcpp, name='post-save-cpp'),
    path('post/save/java', SaveViewjava, name='post-save-java'),
    path('post/save/python', SaveViewpython, name='post-save-python'),
    path('saved-posts/cpp', AllSaveViewcpp, name='all-save-cpp'),
    path('saved-posts/java', AllSaveViewjava, name='all-save-java'),
    path('saved-posts/python', AllSaveViewPython, name='all-save-python'),
    path('saved-posts/', AllSaveView, name='all-save'),
    path('post/comment/like/', LikeCommentView, name='comment-like'),
    path('post/comment/like/cpp', LikeCommentViewcpp, name='comment-like-cpp'),
    path('post/comment/like/java', LikeCommentViewjava, name='comment-like-java'),
    path('post/comment/like/python', LikeCommentViewpython, name='comment-like-python'),
    path('about/', views.about, name='blog-about'),
    path('company-PDF/', views.companypdf, name='blog-companypdf'),
    path('languages/', views.languages, name='blog-languages'),
    path('randomdsa/', views.randomdsa, name='blog-randomdsa'),
    path('codeforces-random/', views.randomcf, name='blog-randomcf'),
    path('codeforces-rating-qns/', views.randomcfrating, name='blog-randomcfrating'),
    path('codeforces-rating-qns-main/', views.randomcfratingmain, name='blog-randomcfratingmain'),
    path('cfuserdetails/', views.cfuserdetails, name='blog-cfuserdetails'),
    path('cfcontests/', views.cfcontests, name='blog-cfcontests'),
    path('contact/', views.contact, name='blog-contact'),
    path('search/', views.search, name='search'),
    path('^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}), 
    path('^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)